
server.port=8080
spring.datasource.url=jdbc:h2:file:./database/walletdb;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.defer-datasource-initialization=true


app.jwt.secret=my-super-long-secret-key-which-is-very-secure-12345

app.jwt.expiration=86400000

# Supported currencies for initiation
app.supported.currencies=INR,USD,EUR



